### ISSUE TITLE
Running 'npm start' gives "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by claremacrae** [konhi/obsidian-repositories-downloader#2]
Thank you for this repo - it looks really useful.

I started trying it out on a Mac, with perhaps a too-old npm version.

Apologies in advance for any spam email it generates - I thought I would track what I tried here, in case it helps out anyone else, or @konhi, if you already know the solution ...

```bash
npm --version
6.13.4

pwd
.../obsidian-repositories-downloader

npm start

> obsidian-repository-downloader@1.0.0 start /Users/clare/Documents/develop/Obsidian/Tools/obsidian-repositories-downloader
> npm ci && node index.js

added 48 packages in 0.99s
/Users/clare/Documents/develop/Obsidian/Tools/obsidian-repositories-downloader/index.js:2
import fetch from "node-fetch";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! obsidian-repository-downloader@1.0.0 start: `npm ci && node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the obsidian-repository-downloader@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clare/.npm/_logs/2021-10-17T09_04_44_949Z-debug.log
```

**Comment by claremacrae** [comment]
There are lots of suggestions here - I don't (yet) understand how to evaluate them...

https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by konhi** [comment]
Thank you for reporting this issue, providing logs, and possible solution! I'm glad that you find this repository interesting. 😄

It seems that it's indeed a problem with node version! I tried with `node v12.14.1` and it gave me the same error.

- _(if for some reasons you still need to use v12)_ please update it to `v12.22.7` - I tried with that version, and it works!
- use some node version manager, like [nvm](https://github.com/nvm-sh/nvm). It allows you to swap between several nodejs versions, as I did when trying to reproduce this issue.

**Comment by claremacrae** [comment]
Thanks... I tried updating node on my Mac and on an Ubuntu VM, and didn't succeed...

I also tried running this with docker-compose ... lots of time passed, but I couldn't see whether and where any files were downloaded...

**Comment by claremacrae** [comment]
As a suggestion ... Might it be possible for you to add a note in the README telling people what versions of tool(s) your script should work with, so that they can check in advance if they will be able to use it?

**Comment by claremacrae** [comment]
Thanks for the suggestions...

For now, it will be take me less time to instead go back to the Python script I had nearly completed to do the same thing, before I learned about this project.
